const roles = {
  admin: ['ADMIN'],
  all: ['ADMIN', 'TECNICO'],
};

const GESTOR_OPTIONS = ['Roberto Garza', 'Ana Martinez', 'Carlos Ruiz', 'Jorge Gomez'];

const OPTIONAL_FIELD_NAMES = new Set(['telefonoAlternativo', 'telAlternativo', 'comentario', 'foto']);

const withRequiredFields = (modules) =>
  modules.map((module) => ({
    ...module,
    fields: module.fields.map((field) => ({
      ...field,
      required: field.type === 'switch' ? field.required : !OPTIONAL_FIELD_NAMES.has(field.name),
    })),
  }));

const baseModules = [
  {
    key: 'usuarios',
    path: 'usuarios',
    section: 'Catalogos',
    title: 'Usuarios',
    description: 'Gestion de accesos y roles.',
    searchPlaceholder: 'Buscar por nombre, correo o rol...',
    endpoint: '/usuarios',
    roles: roles.admin,
    columns: ['nombre', 'correo', 'rol', 'activo'],
    filterControls: [
      { key: 'rol', type: 'value', field: 'rol', allLabel: 'Todos los tipos' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'nombreUsuario', label: 'Nombre', type: 'text', required: true, lettersOnly: true },
      { name: 'email', label: 'Correo', type: 'email', required: true },
      { name: 'contrasena', label: 'Contrasena', type: 'password', required: true, min: 4 },
      { name: 'tipoUsuario', label: 'Rol', type: 'select', required: true, options: ['ADMIN', 'TECNICO'] },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'clientes',
    path: 'clientes',
    section: 'Catalogos',
    title: 'Clientes',
    description: 'Catalogo de clientes y contactos.',
    searchPlaceholder: 'Buscar por razon social, RFC o gestor...',
    endpoint: '/clientes',
    roles: roles.admin,
    columns: ['razon_social', 'rfc', 'correo', 'telefono', 'gestor', 'activo'],
    filterControls: [
      { key: 'gestor', type: 'value', field: 'gestor', allLabel: 'Todos los gestores' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'razonSocial', label: 'Razon social', type: 'text', required: true },
      { name: 'rfc', label: 'RFC', type: 'text', exactLength: 13, maxLength: 13, uppercase: true },
      { name: 'email', label: 'Correo', type: 'email' },
      { name: 'telefono', label: 'Telefono', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'telefonoAlternativo', label: 'Telefono alternativo', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'gestor', label: 'Gestor', type: 'select', options: GESTOR_OPTIONS },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'cedis',
    path: 'cedis',
    section: 'Catalogos',
    title: 'CEDIS',
    description: 'Centros de distribucion asociados a clientes.',
    searchPlaceholder: 'Buscar por nombre, encargado o telefono...',
    endpoint: '/cedis',
    roles: roles.admin,
    columns: ['nombre', 'cliente', 'region', 'encargado', 'telefono', 'activo'],
    lookups: ['clientes', 'regiones'],
    filterControls: [
      { key: 'cliente', type: 'lookup', source: 'clientes', rowField: 'cliente_id', allLabel: 'Todos los clientes' },
      { key: 'region', type: 'lookup', source: 'regiones', rowField: 'region_id', allLabel: 'Todas las regiones' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'clienteId', label: 'Cliente', type: 'lookup', required: true, source: 'clientes' },
      { name: 'regionId', label: 'Region', type: 'lookup', required: true, source: 'regiones' },
      { name: 'direccion', label: 'Direccion', type: 'textarea' },
      { name: 'encargado', label: 'Encargado', type: 'text', lettersOnly: true },
      { name: 'correo', label: 'Correo', type: 'email' },
      { name: 'telefono', label: 'Telefono', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'telAlternativo', label: 'Telefono alternativo', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'vehiculos',
    path: 'vehiculos',
    section: 'Catalogos',
    title: 'Vehiculos',
    description: 'Unidades asignadas a clientes y CEDIS.',
    searchPlaceholder: 'Buscar por placa o serie...',
    endpoint: '/vehiculos',
    roles: roles.all,
    columns: ['placa', 'serie', 'tipo', 'cliente_nombre', 'cedis_nombre', 'activo'],
    lookups: ['clientes', 'cedis'],
    filterControls: [
      { key: 'cliente', type: 'lookup', source: 'clientes', rowField: 'cliente_id', allLabel: 'Todos los clientes' },
      { key: 'cedis', type: 'lookup', source: 'cedis', rowField: 'cedis_id', allLabel: 'Todos los CEDIS' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'placa', label: 'Placa', type: 'text', required: true },
      { name: 'serie', label: 'Serie', type: 'text', required: true },
      {
        name: 'tipo',
        label: 'Tipo',
        type: 'select',
        required: true,
        options: ['CAMION RABON (4x2) DOBLE RODADA TRASERA'],
      },
      { name: 'clienteId', label: 'Cliente', type: 'lookup', required: true, source: 'clientes' },
      { name: 'cedisId', label: 'CEDIS', type: 'lookup', required: true, source: 'cedis' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'verificentros',
    path: 'verificentros',
    section: 'Catalogos',
    title: 'Verificentros',
    description: 'Puntos de verificacion y responsables.',
    searchPlaceholder: 'Buscar por nombre, clave o responsable...',
    endpoint: '/verificentros',
    roles: roles.admin,
    columns: ['nombre', 'clave', 'region', 'responsable', 'telefono', 'activo'],
    lookups: ['regiones'],
    filterControls: [
      { key: 'region', type: 'lookup', source: 'regiones', rowField: 'region_id', allLabel: 'Todas las regiones' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'claveVerificentro', label: 'Clave', type: 'text' },
      { name: 'regionId', label: 'Region', type: 'lookup', required: true, source: 'regiones' },
      { name: 'direccion', label: 'Direccion', type: 'textarea' },
      { name: 'responsable', label: 'Responsable', type: 'text', lettersOnly: true },
      { name: 'correo', label: 'Correo', type: 'email' },
      { name: 'telefono', label: 'Telefono', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'telAlternativo', label: 'Telefono alternativo', type: 'text', digitsOnly: true, exactLength: 10, maxLength: 10 },
      { name: 'horario', label: 'Horario', type: 'text' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'notas',
    path: 'notas',
    section: 'Operaciones',
    title: 'Notas',
    description: 'Contratos y seguimiento de notas activas.',
    createTitle: 'Nueva Nota',
    editTitle: 'Editar Nota',
    saveLabel: 'Guardar',
    updateLabel: 'Actualizar',
    searchPlaceholder: 'Buscar por folio o cliente...',
    endpoint: '/notas',
    roles: roles.admin,
    columns: ['folio', 'cliente_nombre', 'verificentro_nombre', 'tipo_pago', 'anticipo', 'pagado_completo'],
    lookups: ['clientes', 'verificentros'],
    bulkActions: [
      { label: 'Marcar pagadas', action: 'pay', endpoint: '/notas/pagar-masivo' },
      { label: 'Cancelar notas', action: 'delete', endpoint: '/notas/eliminar-masivo' },
    ],
    filterControls: [
      { key: 'cliente', type: 'lookup', source: 'clientes', rowField: 'cliente_id', allLabel: 'Todos los clientes' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'folio', label: 'Folio', type: 'text', required: true },
      { name: 'clienteId', label: 'Cliente', type: 'lookup', required: true, source: 'clientes' },
      { name: 'verificentroId', label: 'Verificentro', type: 'lookup', required: true, source: 'verificentros' },
      { name: 'tipoPago', label: 'Tipo pago', type: 'select', required: true, options: ['EFECTIVO', 'DEPOSITO', 'TRANSFERENCIA', 'TARJETA', 'CREDITO'] },
      { name: 'anticipo', label: 'Anticipo ($)', type: 'number', required: true },
      { name: 'fechaContrato', label: 'Fecha contrato', type: 'date', required: true },
      { name: 'fechaVigencia', label: 'Fecha vigencia', type: 'date', required: true },
      { name: 'pagadoCompleto', label: 'Pagado completo', type: 'switch' },
      { name: 'atendio', label: 'Atendio', type: 'text', required: true, lettersOnly: true },
      { name: 'reviso', label: 'Reviso', type: 'text', required: true, lettersOnly: true },
      { name: 'comentario', label: 'Comentario', type: 'textarea' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'verificaciones',
    path: 'verificaciones',
    section: 'Operaciones',
    title: 'Verificaciones',
    description: 'Resultados de inspecciones y dictamenes.',
    searchPlaceholder: 'Buscar por folio, unidad o materia...',
    endpoint: '/verificaciones',
    roles: roles.all,
    columns: ['nota_folio', 'unidad', 'materia', 'folio', 'fecha', 'resultado'],
    lookups: ['notas', 'vehiculos'],
    filterControls: [
      { key: 'materia', type: 'value', field: 'materia', allLabel: 'Todas las materias' },
      { key: 'resultado', type: 'value', field: 'resultado', allLabel: 'Todos los resultados' },
    ],
    fields: [
      { name: 'notaId', label: 'Nota', type: 'lookup', required: true, source: 'notas' },
      { name: 'vehiculoId', label: 'Vehiculo', type: 'lookup', required: true, source: 'vehiculos' },
      { name: 'materia', label: 'Materia', type: 'select', required: true, options: ['MOTRIZ', 'ARRASTRE', 'GASOLINA', 'HUMO'] },
      { name: 'precio', label: 'Precio', type: 'number' },
      { name: 'multa', label: 'Multa', type: 'number' },
      { name: 'folioVerificacion', label: 'Folio', type: 'text' },
      { name: 'fechaVerificacion', label: 'Fecha', type: 'date' },
      { name: 'dictamen', label: 'Dictamen', type: 'select', required: true, options: ['APROBADO', 'PENDIENTE', 'REPROBADO'] },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'costos',
    path: 'costos',
    section: 'Finanzas',
    title: 'Costos',
    description: 'Tarifas por cliente y materia.',
    searchPlaceholder: 'Buscar por cliente, materia o encargado...',
    endpoint: '/costos',
    roles: roles.admin,
    columns: ['cliente_nombre', 'materia', 'costo', 'encargado', 'atiende_y_cobra', 'activo'],
    lookups: ['clientes'],
    filterControls: [
      { key: 'cliente', type: 'lookup', source: 'clientes', rowField: 'cliente_id', allLabel: 'Todos los clientes' },
      { key: 'materia', type: 'value', field: 'materia', allLabel: 'Todas las materias' },
      { key: 'activo', type: 'status', allLabel: 'Todos los estados' },
    ],
    fields: [
      { name: 'clienteId', label: 'Cliente', type: 'lookup', required: true, source: 'clientes' },
      { name: 'materia', label: 'Materia', type: 'text', required: true },
      { name: 'costo', label: 'Costo', type: 'number', required: true },
      { name: 'encargado', label: 'Encargado', type: 'text', lettersOnly: true },
      { name: 'atiendeYCobra', label: 'Atiende y cobra', type: 'text' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'transacciones',
    path: 'transacciones',
    section: 'Finanzas',
    title: 'Transacciones',
    description: 'Finanzas y estatus de pago.',
    searchPlaceholder: 'Buscar por nota, placa o materia...',
    endpoint: '/transacciones',
    roles: roles.admin,
    columns: ['nota_folio', 'placa', 'materia', 'precio', 'tipo_pago', 'pagado'],
    lookups: ['notas', 'vehiculos'],
    disableEdit: true,
    bulkActions: [
      { label: 'Marcar pagadas', action: 'pay', endpoint: '/transacciones/pagar-masivo' },
      { label: 'Eliminar transacciones', action: 'delete', endpoint: '/transacciones/eliminar-masivo' },
    ],
    filterControls: [
      { key: 'tipoPago', type: 'value', field: 'tipo_pago', allLabel: 'Todos los pagos' },
      { key: 'pagado', type: 'boolean', field: 'pagado', allLabel: 'Todos los pagos', trueLabel: 'Pagadas', falseLabel: 'No pagadas' },
    ],
    fields: [
      { name: 'notaId', label: 'Nota', type: 'lookup', required: true, source: 'notas' },
      { name: 'vehiculoId', label: 'Vehiculo', type: 'lookup', required: true, source: 'vehiculos' },
      { name: 'materia', label: 'Materia', type: 'text', required: true },
      { name: 'precio', label: 'Precio', type: 'number', required: true },
      { name: 'tipoPago', label: 'Tipo de pago', type: 'text' },
      { name: 'cotizacion', label: 'Cotizacion', type: 'text' },
      { name: 'folio', label: 'Folio', type: 'text' },
      { name: 'fechaFolio', label: 'Fecha folio', type: 'date' },
      { name: 'fechaPedido', label: 'Fecha pedido', type: 'date' },
      { name: 'cuentaDeposito', label: 'Cuenta deposito', type: 'text' },
      { name: 'numeroFactura', label: 'Factura', type: 'text' },
      { name: 'pagado', label: 'Pagado', type: 'switch' },
      { name: 'pendiente', label: 'Pendiente', type: 'switch' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
  {
    key: 'pedidos',
    path: 'pedidos',
    section: 'Finanzas',
    title: 'Pedidos',
    description: 'Envios y evidencias de entrega.',
    searchPlaceholder: 'Buscar por nota, guia o cliente...',
    endpoint: '/pedidos',
    roles: roles.admin,
    columns: ['nota_folio', 'cliente_nombre', 'fecha_envio', 'numero_guia', 'estatus_envio', 'recibio'],
    lookups: ['notas'],
    filterControls: [
      { key: 'estatus', type: 'value', field: 'estatus_envio', allLabel: 'Todos los estatus' },
    ],
    fields: [
      { name: 'notaId', label: 'Nota', type: 'lookup', required: true, source: 'notas' },
      { name: 'fechaEnvio', label: 'Fecha de envio', type: 'date' },
      { name: 'numeroGuia', label: 'Numero de guia', type: 'text' },
      { name: 'recibio', label: 'Recibio', type: 'text', lettersOnly: true },
      { name: 'foto', label: 'Foto / evidencia', type: 'text' },
      { name: 'estatusEnvio', label: 'Estatus', type: 'select', options: ['PENDIENTE', 'ENVIADO', 'ENTREGADO', 'INCIDENCIA'] },
      { name: 'comentario', label: 'Comentario', type: 'textarea' },
      { name: 'activo', label: 'Activo', type: 'switch' },
    ],
  },
];

export const MODULES = withRequiredFields(baseModules);
